<!-- Generated by scripts/build_profile.py. Edit config/, content/, or templates/README.md.tpl. -->

<picture>
  <source media="(prefers-reduced-motion: reduce) and (max-width: 600px)" srcset="assets/terminal-mobile-static.svg">
  <source media="(prefers-reduced-motion: reduce)" srcset="assets/terminal-static.svg">
  <source media="(max-width: 600px)" srcset="assets/terminal-mobile.svg">
  <img src="assets/terminal.svg" width="100%" alt="$BANNER_ALT">
</picture>

---

## Contact

$CONTACTS

---

## About Me

$ABOUT

---

## Tech Stack

$STACK

---

## Featured Projects

$PROJECTS

---

## Activity & Contributions

<picture>
  <source media="(prefers-color-scheme: dark)" srcset="assets/contributions/snake-dark-static.svg">
  <img src="assets/contributions/snake-static.svg" width="100%" alt="GitHub contribution calendar, from empty days to highest activity.">
</picture>

[![GitHub statistics: rank, commits and pull requests](assets/stats/github.svg)]($GITHUB_URL)

$STATS_CAPTION
$WIDGETS

---

## Code Philosophy

```c
if (opening_brace_on_same_line) {
    respect++;
}
```

*Last in, first out.*

---

## Hall of Fame

<picture>
  <source media="(prefers-reduced-motion: reduce) and (max-width: 600px)" srcset="assets/quotes-mobile-static.svg">
  <source media="(prefers-reduced-motion: reduce)" srcset="assets/quotes-static.svg">
  <source media="(max-width: 600px)" srcset="assets/quotes-mobile.svg">
  <img src="assets/quotes.svg" width="100%" alt="$QUOTES_ALT">
</picture>
