<!-- Generated by scripts/build_profile.py. Edit config/, content/, or templates/README.md.tpl. -->

<picture>
  <source media="(prefers-reduced-motion: reduce) and (max-width: 600px)" srcset="assets/terminal-mobile-static.svg">
  <source media="(prefers-reduced-motion: reduce)" srcset="assets/terminal-static.svg">
  <source media="(max-width: 600px)" srcset="assets/terminal-mobile.svg">
  <img src="assets/terminal.svg" width="100%" alt="$BANNER_ALT">
</picture>

$CONTACTS

## About Me

$ABOUT

## Tech Stack

$STACK

## Featured Projects

| Project | What it solves |
| --- | --- |
$PROJECTS

## Activity & Contributions

<picture>
  <source media="(prefers-reduced-motion: reduce) and (prefers-color-scheme: dark)" srcset="assets/contributions/snake-dark-static.svg">
  <source media="(prefers-reduced-motion: reduce)" srcset="assets/contributions/snake-static.svg">
  <source media="(prefers-color-scheme: dark)" srcset="assets/contributions/snake-dark.svg">
  <img src="assets/contributions/snake.svg" width="100%" alt="Contribution calendar animated as a snake; a static calendar is shown with reduced motion.">
</picture>

[![GitHub statistics: rank, commits and pull requests](assets/stats/github.svg)]($GITHUB_URL)

$STATS_CAPTION

## Hall of Fame

<details>
<summary>💬 View intercepted transmissions — Quotes</summary>

$QUOTES

</details>
$WIDGETS
## Code Philosophy

```c
if (opening_brace_on_same_line) {
    respect++;
}
```

*Last in, first out.*
