<!doctype html>
<!-- Generated by scripts/build_profile.py. Edit templates/site.html.tpl. -->
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="theme-color" content="$SURFACE">
    <meta name="description" content="$DESCRIPTION">
    <title>$TITLE</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="./theme.css">
    <link rel="stylesheet" href="./styles.css">
    <script src="./app.js" defer></script>
  </head>
  <body>
    <a class="skip-link" href="#interest-links">Skip to contact links</a>
    <main class="page-shell">
      <article class="profile-card" aria-labelledby="profile-title">
        <h1 id="profile-title" class="visually-hidden">$TITLE</h1>
        <picture class="terminal-preview">
          <source media="(prefers-reduced-motion: reduce) and (max-width: 600px)" srcset="./assets/terminal-mobile-static.svg">
          <source media="(prefers-reduced-motion: reduce)" srcset="./assets/terminal-static.svg">
          <source media="(max-width: 600px)" srcset="./assets/terminal-mobile.svg">
          <img src="./assets/terminal.svg" alt="$DESCRIPTION" width="880">
        </picture>

        <section class="interest-links" id="interest-links" aria-labelledby="links-title">
          <div class="section-heading">
            <span class="prompt" aria-hidden="true">~ $$</span>
            <h2 id="links-title">Contact Links</h2>
          </div>

          <nav class="link-grid" aria-label="Contact links">
$CONTACTS
          </nav>

          <p class="copy-feedback" id="copy-feedback" role="status" aria-live="polite" aria-atomic="true"></p>
          <p class="manual-copy" id="manual-copy" hidden>Could not copy. Select the email link to copy the address manually.</p>
        </section>
      </article>
      <p class="page-note"><span aria-hidden="true">//</span> Last in, first out.</p>
    </main>
  </body>
</html>
