"""Generate the web card's CSS custom properties from the shared palette."""

from profile_config import COLOR_KEYS


def render(theme):
    aliases = {"surface": "card"}
    lines = ["/* Generated by scripts/build_profile.py. Edit config/theme.json. */", ":root {"]
    for key in COLOR_KEYS:
        name = aliases.get(key, key).replace("_", "-")
        lines.append(f"  --{name}: {theme[key]};")
    return "\n".join(lines + ["}", ""])
